### ISSUE TITLE
./start.sh returns "[screen is terminating]"

### ISSUE THREAD

**Issue by acarou** [officialrealTM/mcserver_installer#10] opened 2024-12-02 16:29 UTC
## Description

I encountered an issue while setting up a Minecraft Forge 1.20.1 server (Forge version 47.3.0) on my VPS running Ubuntu 22.04 LTS. When I run the ./start.sh script, I immediately receive the message: `[screen is terminating]`
---
## Steps to Reproduce
1. Followed the official installation tutorial for Forge 1.20.1 (version 47.3.0).
2. Executed ./start.sh to launch the server.

## Actual Behavior
The screen process terminates right after running ./start.sh, displaying the message `[screen is terminating].`

## Additional Information
- Operating System: Ubuntu 22.04 LTS
- Forge Version: 47.3.0
- Minecraft Version: 1.20.1
- Server Configuration: Default setup following the tutorial.
- Don't use docker (like #7)

**Comment by officialrealTM** [comment] 2024-12-02 18:47
Hello,

Thank you for your message.
I have just set up a fresh Ubuntu 22.04 server and installed my script there.
As I could see from your specified Forge version, you tried to install a Minecraft Forge 1.20.1 server with Forge version 47.3.0.
I did exactly this on my fresh Ubuntu instance and did not encounter any problems.

In short: I cannot reproduce your error.
However, I can offer you to join my [Discord](https://realtm.link/discord).
There you can open a support ticket and we could look over it together to find any bugs.

I have a few more questions to help you narrow down your problem:
- Are you using a fresh Ubuntu instance or a fresh Ubuntu server or are you running other software on it?
- Have you tried installing a Minecraft server or Java elsewhere before? Did you follow other instructions or did you use my script directly?

I would close the issue now. As mentioned above, you are welcome to contact me on my Discord.

Kind regards

realTM

**Closed as completed** 2024-12-02 18:47 UTC

**Comment by acarou** [comment] 2024-12-05 13:06
I may have found the solution to my problem. 

After upgrading Ubuntu from 20.04 to 22.04, it seems something related to IPv4/IPv6 might have changed in the system configuration. 

Adding `server-ip=0.0.0.0` instead of leaving `server-ip=` empty in the **server.properties** file resolved the issue for me.
